[caps]
energy = 100        # max limit of energy
hitpoints = 100     # max hitpoints
level = 100         # max level

[display]
size = [1280, 720]
caption = "Kater"

[fonts]
player_attribute_font_size = 36
sidebar_font_size = 24
content_font_size = 28
inventory_font_size = 16

[globals]
seed = 38           # for reproducibility

[rates]
base_energy_refill = 1          # how much energy is going to refill per 1 time unit
base_hitpoints_refill = 1       # how much hitpoints is going to refill per 1 time unit
energy = 100          # 1 energy per 1 second
hitpoints = 100       # 1 hitpoints per 1 second

[inventory]
size = 12

[explore]
short_energy = 10               # energy cost of the Short explore action
short_duration = 10000          # 10s
short_experience = 5            # how much experience is awarded per finished short explore action
medium_energy = 20              # energy cost of the Medium explore action
medium_duration = 20000         # 20s
medium_experience = 20          # how much experience is awarded per finished medium explore action
long_energy = 30                # energy cost of the Long explore action
long_duration = 30000           # 30s
long_experience = 30            # how much experience is awarded per finished long explore action