sidebar = ["Inventory", "Travel", "Skills", "Explore", "Export"]
skills = ["mining", "woodcutting", "fishing", "herbalism", "divination"]

[caps]
energy = 100        # max limit of energy
hitpoints = 100     # max hitpoints
level = 100         # max level

[display]
size = [1280, 720]
caption = "Kater"

[fonts]
player_attribute_font_size = 36
sidebar_font_size = 24
content_font_size = 28
inventory_font_size = 16
skills_font_size = 18
explore_font_size = 20

[globals]
seed = 38           # for reproducibility

[rates]
base_energy_refill = 1          # how much energy is going to refill per 1 time unit
base_hitpoints_refill = 1       # how much hitpoints is going to refill per 1 time unit
energy = 1000                   # 1 energy per 1 second
hitpoints = 1000                # 1 hitpoints per 1 second

[inventory]
size = 12

[mining]
items = ["Copper Ore", "Silver Ore"]
energy = [5, 10]
duration = [5000, 10000]
experience = [1, 2]

[woodcutting]
items = ["Oak Log", "Maple Log"]
energy = [5, 10]
duration = [5000, 10000]
experience = [1, 2]

[fishing]
items = ["Carp", "Salmon"]
energy = [5, 10]
duration = [5000, 10000]
experience = [1, 2]

[herbalism]
items = ["Mugwort", "Thistle"]
energy = [5, 10]
duration = [5000, 10000]
experience = [1, 2]

[divination]
items = ["Quartz", "Jade"]
energy = [5, 10]
duration = [5000, 10000]
experience = [1, 2]

[explore]
energy = [10, 20, 30]               # energy cost
duration = [5000, 10000, 15000]     # duration in ms
experience = [10, 20, 30]           # experience per one action