version: '3.6'
services:
  postgres:
    image: postgres:13
    container_name: postgres
    env_file:
      - .env.local
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - kater-network
    ports:
      - "4000:5432"

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    volumes:
      - pgadmin_date:/var/lib/pgadmin
    env_file:
      - .env.local
    networks:
      - kater-network

  kater-be:
    image: python:latest
    container_name: django
    env_file:
      - .env.local
    working_dir: "/app" 
    volumes:
      - ./backend/kater:/app
    # command: bash -c "sleep infinity"
    command: > 
      bash -c "
        pip install --trusted-host pypi.python.org --upgrade pip && 
        pip install --trusted-host pypi.python.org --no-cache-dir -r requirements.txt &&
        python manage.py makemigrations api &&
        python manage.py migrate && 
        python manage.py runserver 0.0.0.0:8000
      "
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    networks:
      - kater-network
    
  kater-fe:
    image: "node:22.3.0-alpine3.19"
    container_name: vue
    working_dir: "/app" 
    ports: 
      - "80:80"
    volumes:
    - ./frontend/Kater:/app
    command: > 
      sh -c "
        npm install &&
        npm run dev -- --host --port 80
      "

volumes:
  postgres_data:
  pgadmin_date:

networks:
  kater-network: