version: '3.6'
services:
  postgres:
    image: postgres:13
    container_name: postgres
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - kater-network
    ports:
      - "4000:5432"
  
  backend:
    hostname: kater-be
    container_name: kater-server
    build:
      dockerfile: Dockerfile-server
      context: .
      target: kater-be
    env_file:
      - .env
    networks:
      - kater-network

  frontend:
    hostname: kater-fe
    container_name: kater
    build:
      dockerfile: Dockerfile-server
      context: .
      target: vue-build
    env_file:
      - .env
    networks:
      - kater-network

volumes:
  postgres_data:
  pgadmin_date:

networks:
  kater-network: