import pygame

REFILL_ENERGY = pygame.USEREVENT + 1
REFILL_HITPOINTS = pygame.USEREVENT + 2
SHORT_EXPLORE = pygame.USEREVENT + 3
MEDIUM_EXPLORE = pygame.USEREVENT + 4
LONG_EXPLORE = pygame.USEREVENT + 5