import pygame

# Basic attributes
REFILL_ENERGY = pygame.USEREVENT + 1
REFILL_HITPOINTS = pygame.USEREVENT + 2

# Explore actions
EXPLORE_FINISHED = pygame.USEREVENT + 3

ORE_MINED = pygame.USEREVENT + 4
LOG_CHOPPED = pygame.USEREVENT + 5
FISH_CAUGHT = pygame.USEREVENT + 6
HERB_PICKED = pygame.USEREVENT + 7
CRYSTAL_GATHERED = pygame.USEREVENT + 8

# UI stuff
BLINK_INVENTORY_UPDATE_TEXT = pygame.USEREVENT + 9