#name: Build Kater with Pygbag
#on:
#  push:
#    branches:
#      - main
#    workflow_dispatch:
#permissions:
#  contents: write
#
#jobs:
#  build-pygbag:
#    name: Kater Game
#    runs-on: ubuntu-latest
#
#    steps:
#    - uses: actions/checkout@v4
#    - name: Checkout
#      run: |
#            echo "Attempting to install pygbag"
#            python -m pip install pygbag
#            python -m pygbag --build $GITHUB_WORKSPACE
#
#    - name : "Upload to GitHub pages branch gh-pages"
#      uses: JamesIves/github-pages-deploy-action@4.1.7
#      with:
#        branch: origin/gh-pages
#        folder: build/web